### ISSUE TITLE
Building randomly breaks with Carthage

### ISSUE THREAD

**Issue by nickygerritsen** [soffes/Crypto#15]
If I use Crypto as a dependency buidling randomly breaks when running `carthage update` with the following in the log:

```
Build settings from command line:
    BITCODE_GENERATION_MODE = bitcode
    CODE_SIGN_IDENTITY = 
    CODE_SIGNING_REQUIRED = NO
    ONLY_ACTIVE_ARCH = NO
    SDKROOT = appletvos9.1

=== BUILD TARGET CommonCrypto-OSX OF PROJECT Crypto WITH CONFIGURATION Release ===

Check dependencies
target 'CommonCrypto-OSX' has bitcode disabled (ENABLE_BITCODE = NO), but it is required for the 'appletvos' platform
```

It seems it wants to build the OS X target for a tvos SDK, which of course fails.

I remember having this problem before and in one of my PR's I used to have fixed this by removing and recreating some (or all) targets in the project.

However because I redid that whole PR I forgot to do that again and forgot what it exactly was.

I might be able to fix it again, but was also wondering if other people have the same problem.

**Comment by loudnate** [comment]
:+1: I'm having the same issue.

**Comment by soffes** [comment]
I never seen this. Are you guys still having this issue?

**Comment by nickygerritsen** [comment]
I'm not actively using this currently, so I have no idea if it still happens, sorry.
