### ISSUE TITLE
ld: warning: directory not found for option

### ISSUE THREAD

**Issue by ajarzebowski** [soffes/Crypto#17]
Hi,

I am getting error while performing carthage update on project. Cartfile contains only

`github "soffes/Crypto"`

The error:

`ld: warning: directory not found for option '-L/Applications/Xcode.app/Contents/Developer/Platforms/WatchOS.platform/Developer/SDKs/WatchOS2.2.sdk/usr/lib/system'
ld: warning: directory not found for option '-L/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.3.sdk/usr/lib/system'
ld: warning: directory not found for option '-L/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.3.sdk/usr/lib/system'
`

Occasionally without any reason I am also getting:

*\* CLEAN FAILED **

The following build commands failed:
    Check dependencies
(1 failure)
*\* BUILD FAILED **

The following build commands failed:
    Check dependencies
(1 failure)
ld: warning: directory not found for option '-L/Applications/Xcode.app/Contents/Developer/Platforms/WatchOS.platform/Developer/SDKs/WatchOS2.2.sdk/usr/lib/system'
A shell task (/usr/bin/xcrun xcodebuild -project /Users/user/Downloads/ios-sdk/Carthage/Checkouts/Crypto/Crypto.xcodeproj -scheme Crypto-tvOS -configuration Release -sdk appletvos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build) failed with exit code 65:
*\* CLEAN FAILED **

The following build commands failed:
    Check dependencies
(1 failure)
*\* BUILD FAILED **

The following build commands failed:
    Check dependencies
(1 failure)

It's showing while doing "carthage update" but if I run it again it's showing the first error again.

I am running "carthage update" as normal user.

**Comment by soffes** [comment]
It looks like you have an outdated version of Xcode. Try upgrading to Xcode 8.1 which is supported in Crypto 0.5.1. Feel free to reopen if you're still having trouble!
