### ISSUE TITLE
Carthage Update fails on tvOS

### ISSUE THREAD

**Issue by teppotk** [soffes/Crypto#18]
Hi, I'm a bit of a newbie with this and Carthage, but it seems that "carthage update" command fails at tvOS stage like this:

---

$ carthage update
**\* Cloning Crypto
**\* Checking out Crypto at "v0.3.0"
**\* xcodebuild output can be found in /var/folders/cv/y8tpg3v946x9h58ctz2yqg700000gn/T/carthage-xcodebuild.JUuVTA.log
**\* Building scheme "CommonCrypto-watchOS" in Crypto.xcodeproj
**\* Building scheme "CommonCrypto-iOS" in Crypto.xcodeproj
**\* Building scheme "CommonCrypto-OSX" in Crypto.xcodeproj
**\* Building scheme "Crypto-tvOS" in Crypto.xcodeproj
*\* CLEAN FAILED **

…

The following build commands failed:
    Check dependencies
(1 failure)
A shell task (/usr/bin/xcrun xcodebuild -project /Users/…/Carthage/Checkouts/Crypto/Crypto.xcodeproj -scheme Crypto-tvOS -configuration Release -sdk appletvos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build) failed with exit code 65:
## 

As a result (I believe) the tvOS folder is missing from carthage/build. This is sad because I'd need CommonCrypto especially for tvOS. :)

I apologise if this is just my ignorance on some topic, or I'm missing something, but as of now I don't seem to get it going for tvOS by following Carthage installation guide.

**Comment by soffes** [comment]
Do you have a tvOS simulator for the selected Xcode? I'm fairly certain that's the issue. This is working for me just fine in version 0.5.1.

Feel free to reopen if you're still having trouble!
