### ISSUE TITLE
Doubt : How to get sha1 of Data as a String

### ISSUE THREAD

**Issue by speaktoalvin** [soffes/Crypto#24]
Right now we have methods which gives sha1 of Data as Data. So I have tried converting it into String by UTF8 Encoding & also ASCII, but it seems that both didn't produce the proper String.

How can I get sha1 as String for Data?

**Comment by soffes** [comment]
Internally, I convert Data to a hex string with [this](https://github.com/soffes/Crypto/blob/master/Crypto/Data%2BCrypto.swift#L64).

Does that work for you? I can make a public version of the Data to String when I get time.

**Comment by alvinvarghese** [comment]
So you saying ```hex``` value and ```SHA1``` value of a ```Data``` are same?

**Comment by soffes** [comment]
Look at the source for the String one. It converts the string to Data, calls `sha1` on the Data, and then calls `hex` on the Data to convert it back to a string.

**Comment by speaktoalvin** [comment]
I am kind of confused here, Sorry.

`let dataObject = Data()`
`let stringHEX = dataObject.hex`
 `let sha1 = stringHEX.sha1` 

You meant this right?

**Comment by soffes** [comment]
No.

> calls `sha1` on the Data, and then calls hex on the Data to convert it back to a string
