### ISSUE TITLE
Console warning in Xcode 8 & Swift 3

### ISSUE THREAD

**Issue by speaktoalvin** [soffes/Crypto#25]
I have been seeing this warning in `Xcode 8` from the last two days. I am using `Crypto` in my `Swift 3` project. I would like to know why this warning shows up and is there anything I have to worry about?

```
warning: Swift error in module Crypto.
Debug info from this module will be unavailable in the debugger.
```

**Comment by soffes** [comment]
I've seen this in several libraries. I think it's an issue with Carthage. It's definitely not specific to Crypto.
