### ISSUE TITLE
Prebuilt binary via Carthage incompatible with Swift 3.0.1

### ISSUE THREAD

**Issue by danielrhodes** [soffes/Crypto#26]
This is as of XCode 8.1. Fix should be as simple as re-archiving the binary created by carthage.

If anybody else is having this problem, you can run the following to build from source and get around this problem.

`carthage update --no-use-binaries`

**Comment by soffes** [comment]
[Version 0.5.1](https://github.com/soffes/Crypto/releases/tag/v0.5.1) has been released with a prebuilt binary for Swift 3.0.1.

By the way, it's Xcode not XCode :)

**Comment by danielrhodes** [comment]
_hangs head in shame_
