### ISSUE TITLE
Digest property return "" in Swift 3.1

### ISSUE THREAD

**Issue by r-plus** [soffes/Crypto#28]
All of the digest(MD2, MD4, MD5, SHA1, SHA224, SHA256, SHA384, SHA512) for String extension return `""`.

```
"sam".sha1 // ""
```

Crypto: 0.5.1
CommonCrypto: 1.1.0
Xcode: 8.3
Swift: 3.1

**Comment by r-plus** [comment]
Thanks for quickly fix.

**Comment by r-plus** [comment]
In our internal test, 0.5.2 still return `""`.

**Comment by r-plus** [comment]
Sorry, its my mistake.
0.5.2 is correct 👍

**Comment by soffes** [comment]
Good! Glad you got it! I spent the last half hour trying to make sure it worked (and even [made a video](https://www.youtube.com/watch?v=etOkXNKH-Yw)). Glad you figured it out! Sorry for that weird bug :)
