### ISSUE TITLE
Bitcode Warning

### ISSUE THREAD

**Issue by aputinski** [soffes/Crypto#4]
Currently importing this with Xcode 7 / iOS 9 and getting the following warning:

`ld: warning: URGENT: all bitcode will be dropped because 'Carthage/Build/iOS/CommonCrypto.framework/CommonCrypto' was built without bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. Note: This will be an error in the future.`

Is this something that needs to be updated in the library or is this a Carthage issue?

**Comment by soffes** [comment]
for now:

``` ruby
github "soffes/Crypto" "master"
```

`master` requires Xcode 7 now, so waiting to release until that GMs

**Comment by aputinski** [comment]
Thanks!
